version: "3.8"

services:
  python-app:
    image: keycloak-flask:0.1
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DISCOVERY_URL: ${DISCOVERY_URL}
    ports:
      - 5000:5000